# PA8, Radjamin Hukom, V1, Spring 2023

## A.

In [5]:
import numpy as np
l1 = [10,20,30,40]
x1 = np.array(l1)
x1.resize(2,2)
x1

array([[10, 20],
       [30, 40]])

In [6]:
x2 = np.add(x1,100)
x2

array([[110, 120],
       [130, 140]])

In [7]:
x3 = np.multiply(x1,5)
x3

array([[ 50, 100],
       [150, 200]])

In [9]:
x4= np.sqrt(x1)
x4

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### OR

In [11]:
x5= np.add(x1,100)
print("1.",x5)
x5= np.multiply(x5,5)
print("2.",x5)
x5= np.sqrt(x5)
print("3.",x5)

1. [[110 120]
 [130 140]]
2. [[550 600]
 [650 700]]
3. [[23.4520788  24.49489743]
 [25.49509757 26.45751311]]


## B

In [18]:
x6= np.arange(3,30,3)
x6.resize(3,3)
print(x6)
x7= np.arange(10,20,10/9)
x7.resize(3,3)
print(x7)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[10.         11.11111111 12.22222222]
 [13.33333333 14.44444444 15.55555556]
 [16.66666667 17.77777778 18.88888889]]


In [20]:
x8=np.multiply(x6,x7)
print(x8)

[[ 30.          66.66666667 110.        ]
 [160.         216.66666667 280.        ]
 [350.         426.66666667 510.        ]]


## C

In [21]:
x08=np.load('process1.npy')
x09=np.load('process2.npy')
x10=np.load('process3.npy')
x11=np.load('process4.npy')
x12=np.load('process5.npy')

In [22]:
array1=np.vstack([x08,x09,x10,x11,x12])

In [26]:
print(array1)
a,b,c,d,e=np.hsplit(array1,5)
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())
print(e.mean())

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]
72.0
27.8
45.6
12.0
47.8
